apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: http
    nodePort: 30001
    protocol: TCP
    name: http
  selector:
    app: service-a
